### PR TITLE
Feature: adds a standalone 1804 build

### PR DESCRIPTION
**Pull request by lsh-0**
Formula builds on an 1804 vagrant box without any problems. This PR just adds an 1804 build for Alfred.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Good intention, but a smoke test fails (502 suggests the PHP-FPM instance behind nginx doesn't start).

**Comment by lsh-0** [comment]
investigating

**Comment by lsh-0** [comment]
current problem looks like the vault token issue again

**Comment by giorgiosironi** [comment]
So this was solved yesterday for `observer-formula` and another test build, but it seems to be happening here. Reproducing and investigating.

**Comment by giorgiosironi** [comment]
While the build is running:
```
jenkins@prod--alfred:~$ vault token lookup
Key                 Value
---                 -----
accessor            c25843a5-8413-2f44-8c58-78819f12ebdb
creation_time       1553584511
creation_ttl        1h
display_name        approle
entity_id           2c243e1f-0988-542b-0ed4-bb4f2d14d8b3
expire_time         2019-03-26T08:15:11.870160765Z
explicit_max_ttl    0s
id                  6e329251-d823-0412-c305-222840c04569
issue_time          2019-03-26T07:15:11.8701602Z
meta                map[role_name:jenkins]
num_uses            0
orphan              true
path                auth/approle/login
policies            [default jenkins-containers jenkins-elife-alfred master-server]
renewable           true
ttl                 1m51s
```
That 1m51s doesn't look good, if Jenkins tries to use the token it could expire. The re-creation of the token that happens at the start of the build has some problems.

**Comment by giorgiosironi** [comment]
Vault problem solved for the time being, fails only on 18.04 now. This project has to be ported to containers so if it's anything PHP-specific hold off and we'll port it first. That would make the formula much simpler.

Arguably we could take that route even as the first choice?

**Comment by lsh-0** [comment]
> This project has to be ported to containers so if it's anything PHP-specific hold off and we'll port it first.

Chris requested we do that with the journal formula as well. Do you see these projects as being deployed on the EKS work you're doing?

**Comment by giorgiosironi** [comment]
> Do you see these projects as being deployed on the EKS work you're doing?

No, not stable enough yet. The target would be EC2 Ubuntu 18.04 with a Docker container on top. The problem here may be that if we switch to 18.04 without the container it may change the PHP version to an incompatible one.

**Comment by lsh-0** [comment]
ok, I'll take a look at containerising the recommendations project. I'm still somewhat antagonistic towards Docker, do you have any examples of elife projects that I could use as a guide?

**Comment by lsh-0** [comment]
I've found [your ticket](https://github.com/elifesciences/issues/issues/4845) and added it as a prerequisite to this

**Comment by lsh-0** [comment]
18.04 is passing now but with the usual php7 errors in head/fresh/update

**Comment by giorgiosironi** [comment]
Now `base` shouldn't fail anymore...

**Comment by giorgiosironi** [comment]
It doesn't.

**Comment by lsh-0** [comment]
premature delete of branch. I'll continue working in it but open another PR

**Comment by lsh-0** [comment]
actually, I'm going through the formula and what is happening now with recommendations and it looks done. Just waiting to be deployed.

I also see the new docker-compose file and the docker files in the recommendations project. This separation of concerns between the project's responsibilities and the formula's. The project describes how to build the container and the formula describes how to configure it...

**Comment by giorgiosironi** [comment]
A Docker image is the ultimate build artifact

**Comment by lsh-0** [comment]
rofl

**Comment by lsh-0** [comment]
I'm working with clojure a lot at the moment and you can get a nicely compiled and bundled jar file as an artifact. There is also some really fantastic and interesting work happening in the GraalVM world in compiling java (+clojure, +php, +python, +...) to tiny native executables that are much much faster.

**Pull request merged**
